In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('netflix_sample_500.csv')

In [7]:
df.shape

(500, 7)

In [8]:
df.columns.tolist()

['title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'duration']

In [9]:
df.head(5)
df.tail(3)

,title,director,cast,country,date_added,release_year,duration
497,Korean Cold Noodle Rhapsody,NaN,Paik Jong-won,NaN,"August 20, 2021",2021,1 Season
498,Look for a Star,Andrew Lau Wai-Keung,"Andy Lau, Qi Shu, Zhang Hanyu, Denise Ho, Domi...",Hong Kong,"December 1, 2018",2009,117 min
499,40 Sticks,Victor Gatonye,"Robert Agengo, Mwaura Bilal, Andreo Kamau, Caj...",Kenya,"November 20, 2020",2019,93 min

In [10]:
df[['title', 'release_year']]

                                title  release_year
0                     Game Over, Man!          2018
1        Arsenio Hall: Smart & Classy          2019
2                            Kazoops!          2017
3                We Are the Champions          2020
4    Pablo Escobar, el patrón del mal          2012
..                                ...           ...
495       Sebastián Marcelo Wainraich          2018
496                      The Mistress          2012
497       Korean Cold Noodle Rhapsody          2021
498                   Look for a Star          2009
499                         40 Sticks          2019

[500 rows x 2 columns]

In [11]:
df.iloc[10:21]

,title,director,cast,country,date_added,release_year,duration
10,"Drugs, Inc.",NaN,Mike Secher,United States,"March 23, 2019",2015,1 Season
11,Den of Thieves,Christian Gudegast,"Gerard Butler, Pablo Schreiber, O'Shea Jackson...",United States,"May 1, 2020",2018,140 min
12,The President's Barber,Chan-sang Lim,"Kang-ho Song, So-ri Moon, Jae-eung Lee, Yeong-...",South Korea,"October 1, 2017",2004,116 min
13,The Dirt,Jeff Tremaine,"Douglas Booth, Iwan Rheon, Colson Baker, Danie...",United States,"March 22, 2019",2019,108 min
14,Brews Brothers,NaN,"Alan Aisenberg, Mike Castle, Carmen Flood, Mar...",United States,"April 10, 2020",2020,1 Season
15,Rodney Carrington: Here Comes the Truth,Brandon Jones,Rodney Carrington,United States,"October 3, 2017",2017,66 min
16,Planet Hulk,Sam Liu,"Rick D. Wasserman, Lisa Ann Beley, Mark Hildre...",United States,"June 1, 2020",2010,81 min
17,Tree Man,"Jon Reiner, Brad Rothschild",NaN,Canada,"November 1, 2016",2015,82 min
18,Ladies First,Uraaz Bahl,NaN,India,"March 8, 2018",2018,40 min
19,King Jack,Felix Thompson,"Charlie Plummer, Cory Nichols, Christian Madse...",United States,"July 1, 2016",2015,81 min
20,"I love you, stupid",Laura Mañá,"Quim Gutiérrez, Natalia Tena, Alfonso Bassave,...",Spain,"May 15, 2020",2019,88 min

In [12]:
df.isnull().sum()

title             0
director        164
cast             41
country          46
date_added        0
release_year      0
duration          0
dtype: int64

df['country'].fillna('Unknown', inplace=True)
df['director'].fillna('Not Available', inplace=True)

In [18]:
df['country'] = df['country'].replace('United States', 'USA')

In [19]:
df

,title,director,cast,country,date_added,release_year,duration
0,"Game Over, Man!",Not Available,"Adam DeVine, Anders Holm, Blake Anderson, Utka...",Unknown,"March 23, 2018",2018,102 min
1,Arsenio Hall: Smart & Classy,Not Available,Arsenio Hall,Unknown,"October 29, 2019",2019,63 min
2,Kazoops!,Not Available,"Reece Pockney, Scott Langley, Alex Babic, Gemm...",Unknown,"May 5, 2017",2017,3 Seasons
3,We Are the Champions,Not Available,NaN,Unknown,"November 17, 2020",2020,1 Season
4,"Pablo Escobar, el patrón del mal",Not Available,"Andrés Parra, Angie Cepeda, Cecilia Navia, Vic...",Unknown,"February 3, 2021",2012,1 Season
...,...,...,...,...,...,...,...
495,Sebastián Marcelo Wainraich,Not Available,Sebastián Marcelo Wainraich,Unknown,"January 26, 2018",2018,49 min
496,The Mistress,Not Available,"John Lloyd Cruz, Bea Alonzo, Hilda Koronel, Ro...",Unknown,"February 27, 2019",2012,132 min
497,Korean Cold Noodle Rhapsody,Not Available,Paik Jong-won,Unknown,"August 20, 2021",2021,1 Season
498,Look for a Star,Not Available,"Andy Lau, Qi Shu, Zhang Hanyu, Denise Ho, Domi...",Unknown,"December 1, 2018",2009,117 min
499,40 Sticks,Not Available,"Robert Agengo, Mwaura Bilal, Andreo Kamau, Caj...",Unknown,"November 20, 2020",2019,93 min

In [20]:
df['years_since_release'] = 2025 - df['release_year']

In [21]:
df.groupby('release_year').size()

release_year
1943     1
1954     1
1960     1
1962     1
1963     1
1969     1
1973     1
1976     1
1978     1
1979     2
1981     1
1982     1
1985     1
1986     2
1988     1
1990     1
1991     1
1992     1
1993     2
1994     1
1996     2
1998     3
1999     1
2001     2
2002     2
2003     2
2004     3
2005     1
2006     6
2007     8
2008     7
2009    14
2010    13
2011     8
2012    12
2013    20
2014    26
2015    29
2016    55
2017    57
2018    75
2019    47
2020    45
2021    39
dtype: int64

In [22]:
df['country'].nunique()

1